### ISSUE TITLE
LocationListener keeps stopping

### ISSUE THREAD

**Issue by meniteesh** [EssamTarik/LocationListener#2]
My App is built successfully but when Starting the app it keeps stopping in android. My all code is same as yours except some version difference:

Package.json:

{
  "name": "Chutiyapa",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-preset-react-native": "4.0.1",
    "jest": "23.6.0",
    "react-test-renderer": "16.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

My android/app/build.gradle:
compileSdkVersion 23
    buildToolsVersion "23.0.1"
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId "LocationListener"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.00"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

except this all other things are same

**Comment by EssamTarik** [comment]
what does the android log say ?

**Comment by meniteesh** [comment]
### **This is my android log:-** 

C:\react-native\LocationListener>react-native log-android
Scanning folders for symlinks in C:\react-native\LocationListener\node_modules (63ms)
Starting the logger (C:\Users\Lenovo-3\AppData\Local\Android\Sdk/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V)...
- waiting for device -
--------- beginning of system
--------- beginning of crash
--------- beginning of main

### **: Log stuck here**

### **This is my react-native run-android log:-**

C:\react-native\LocationListener>react-native run-android
Scanning folders for symlinks in C:\react-native\LocationListener\node_modules (78ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:app:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:app:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:app:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:app:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:app:prepareComFacebookReactReactNative0554Library UP-TO-DATE
:app:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:app:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:bundleDebugJsAndAssets SKIPPED
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Moto G Play - 7.1.1' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 29.469 secs
Running C:\Users\Lenovo-3\AppData\Local\Android\Sdk/platform-tools/adb -s ZY223HX8GC reverse tcp:8081 tcp:8081
Starting the app on ZY223HX8GC (C:\Users\Lenovo-3\AppData\Local\Android\Sdk/platform-tools/adb -s ZY223HX8GC shell am start -n com.locationListener/com.locationListener.MainActivity)...
Starting: Intent { cmp=com.locationListener/.MainActivity }

**Comment by EssamTarik** [comment]
please use `adb logcat` because we can't see the error this way

**Comment by meniteesh** [comment]
**I think its permission issue:**

09-13 13:17:21.423 14158-14158/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.locationListener, PID: 14158
    java.lang.RuntimeException: Unable to create application com.locationListener.MainApplication: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5406)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.os.Parcel.readException(Parcel.java:1637)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:614)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:899)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:472)
        at com.locationListener.MainApplication.onCreate(MainApplication.java:72)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5403)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by EssamTarik** [comment]
Have you added the location permissions to your AndroidManifest.xml
like https://github.com/EssamTarik/LocationListener/blob/master/android/app/src/main/AndroidManifest.xml

if yes, have you granted the app location permissions on the device ?
